# Generated by Django 5.1.1 on 2024-10-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={},
        ),
        migrations.AlterModelManagers(
            name='informations',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='informations',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='informations',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
