# Generated by Django 5.1.3 on 2024-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_informations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='debt',
            field=models.IntegerField(default=0, verbose_name='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informations',
            name='emergencyFund',
            field=models.IntegerField(default=0, verbose_name='0'),
            preserve_default=False,
        ),
    ]
