# Generated by Django 5.1.3 on 2024-12-21 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_goals_rename_informations_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_informations',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(verbose_name='0')),
                ('income', models.IntegerField(verbose_name='0')),
                ('expenses', models.IntegerField(verbose_name='0')),
                ('debt', models.IntegerField(verbose_name='0')),
                ('emergencyFund', models.IntegerField(verbose_name='0')),
            ],
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
